name: 📦 Create and Publish Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 📥 Build Frontend
      run: |
        npm install
        npm run build
    
    - name: 🚀 Deploy to Azure Static Site
      run: |
        npm install -g @azure/static-web-apps-cli
        swa deploy --deployment-token ${{ secrets.AZURE_STATIC_WEB_APP_TOKEN }} --env Production
